### ISSUE TITLE
Malformed repo url breaks package link

### ISSUE THREAD

**Issue by timoxley** [solids/npmsearch#11]
Gets confused when given not-quite-right repo url in package.json such as:

```json
"repository": {
    "type": "git",
    "url": "git://github.com//tmpvar/repl.history"
  },
```

Reproduce by clicking on repl.history in http://npmsearch.com/?q=repl.history (assuming you haven't merged & published https://github.com/tmpvar/repl.history/pull/4)

[![image](https://cloud.githubusercontent.com/assets/43438/6715907/c09161b6-cddc-11e4-8df3-0885905d3236.png)](http://npmsearch.com/?q=repl.history)

On npmjs.com, url is left as-is and will browser will try work it: https://www.npmjs.com/package/repl.history

![image](https://cloud.githubusercontent.com/assets/43438/6715846/6411dbfa-cddc-11e4-8d57-00f9531999a7.png)

Not sure what is best solution.

**Comment by tmpvar** [comment]
ah, this is due to primitive url sanitation in `npm-normalize` https://github.com/solids/npm-normalize/blob/master/index.js#L94

**Comment by tmpvar** [comment]
main issue here is the `//` being interpreted as a protocol.  I've gone through and fixed this in `npm-normalize` by parsing the url first and then applying the replace only on `urlparts.path` - https://github.com/solids/npm-normalize/commit/684c851414c55899c2cefa15b28a5bf33b1b39c1

This however does not fix existing data in elasticsearch so I'll either need to do a full reindex or add similar code to the client

**Comment by tmpvar** [comment]
full re-index achieved
