### ISSUE TITLE
Doesn't support tags with a “-”

### ISSUE THREAD

**Issue by tomekwi** [solids/npmsearch#12]
* http://npmsearch.com/?q=keywords:%22web-component%22
* http://npmsearch.com/?q=keywords:web-component

– none of these work, although [there are plenty modules with such a tag](http://npmsearch.com/?q=web-component).

**Comment by tmpvar** [comment]
good catch, this is a pretty bad issue.

**Comment by tmpvar** [comment]
wrong, 81fbe3767a77839c9b945f212d8cf67dc3a7f7c1 does not close this.

**Comment by tmpvar** [comment]
fixed and deployed with #18 

![screen shot 2015-06-01 at 1 28 38 am](https://cloud.githubusercontent.com/assets/46673/7906722/92f20b56-07fd-11e5-9c48-7255a23ee256.png)
![screen shot 2015-06-01 at 1 28 30 am](https://cloud.githubusercontent.com/assets/46673/7906723/92f9acd0-07fd-11e5-99a9-75c9b409e49e.png)

**Comment by tomekwi** [comment]
Great! :+1:
