### ISSUE TITLE
Some searches break because of query selector

### ISSUE THREAD

**Issue by davej** [solids/npmsearch#14]
For example search for 'port': http://npmsearch.com/?q=port

**Comment by tmpvar** [comment]
gah, thank you for reporting! so weird - I'll look into it

**Comment by tmpvar** [comment]
fixed as of #18 

![screen shot 2015-06-01 at 1 41 20 am](https://cloud.githubusercontent.com/assets/46673/7906836/576c30dc-07ff-11e5-955f-a1514a489770.png)
![screen shot 2015-06-01 at 1 40 10 am](https://cloud.githubusercontent.com/assets/46673/7906837/576e0a10-07ff-11e5-8179-0dc1278dec2c.png)
