### ISSUE TITLE
Provide npmsearch.com also via HTTPS

### ISSUE THREAD

**Issue by simon04** [solids/npmsearch#21]
It would be great to have http://npmsearch.com/ also available via HTTPS.

Free certificates are available via https://startssl.com/ and soon https://letsencrypt.org/.

**Comment by yanaki** [comment]
:+1:

**Comment by zahhak** [comment]
:+1:

**Comment by simon04** [comment]
There is also https://www.globalsign.com/en/ssl/ssl-open-source/

**Comment by tmpvar** [comment]
Seems to be a good amount of traction here and elsewhere, let's do this!

I've signed up for a beta account on letsencrypt.org 

I don't want to judge startssl.com by it's cover but damn, that site's design is horrible.

this repo is currently unlicensed which is definitely a bad thing, so I'll fix that pending a letsencrypt email and submit to globalsign.

If anyone knows other options please let me know!

**Comment by tmpvar** [comment]
In an effort to be transparent (and not look too lazy!) I've gone off and retrieved an SSL cert.  I'll be looking at rolling out SSL support in the next day or two.  Thanks for the push!

**Comment by tmpvar** [comment]
Ok folks!  https://npmsearch.com is now alive and kicking

![screen shot 2015-10-07 at 6 33 07 pm](https://cloud.githubusercontent.com/assets/46673/10353219/9994eec6-6d22-11e5-8e50-45c9c2579b19.png)

and the HTTP api also works under SSL

```
npmsearch‣ curl "https://npmsearch.com/query?q=dom&fields=id" -v | json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.73.237.82...
* Connected to npmsearch.com (192.73.237.82) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: www.npmsearch.com
* Server certificate: GlobalSign Domain Validation CA - SHA256 - G2
* Server certificate: GlobalSign Root CA
> GET /query?q=dom&fields=id HTTP/1.1
> Host: npmsearch.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Date: Wed, 07 Oct 2015 22:36:58 GMT
< Transfer-Encoding: chunked
<
{ [288 bytes data]
100   276    0   276    0     0    984      0 --:--:-- --:--:-- --:--:--   985
* Connection #0 to host npmsearch.com left intact
{
  "results": [
    {
      "id": [
        "zero-dom-utils"
      ]
    },
    {
      "id": [
        "dom-iterators"
      ]
    },
    {
      "id": [
        "select-dom"
      ]
    },
    {
      "id": [
        "dom-anchor-testing"
      ]
    },
    {
      "id": [
        "dom-manipulations"
      ]
    },
    {
      "id": [
        "dom-value"
      ]
    },
    {
      "id": [
        "dom-stub"
      ]
    },
    {
      "id": [
        "dom-walk"
      ]
    },
    {
      "id": [
        "karma-chai-dom"
      ]
    },
    {
      "id": [
        "dom-select"
      ]
    }
  ],
  "total": 5857,
  "from": 0
}
```
