### ISSUE TITLE
Search not indexing package

### ISSUE THREAD

**Issue by sunnycupertino** [solids/npmsearch#28]
This package is not indexed https://github.com/sunnycupertino/cordova-plugin-admob-simple

**Comment by sunnycupertino** [comment]
NPM version here https://www.npmjs.com/package/cordova-plugin-admob-simple

**Comment by tmpvar** [comment]
Oh, good catch.  Looks like `npm2es` hung or something. Indexing the latest now, should be done in a few mins

Thanks!

**Comment by sunnycupertino** [comment]
:-) Groovy
