### ISSUE TITLE
Inconsistent API Results.

### ISSUE THREAD

**Issue by JimtotheB** [solids/npmsearch#30]
Looking to integrate this tool into a project site, came across a few inconsistencies 

http://npmsearch.com/?q=keywords:leveldb,voxel

1 result

http://npmsearch.com/query?q=keywords:leveldb,voxel

No results

http://npmsearch.com/query?q=keywords:leveldb&q=keywords:voxel

175! results

Is there a way to pass in multiple keyword arguments to the JSON API and have it return the correct results?

Also, I suppose this should go into a new issue, but is there a terms of use for the hosted side of this project?

**Comment by tmpvar** [comment]
There is some sugar on the web interface that allows people to type in queries, one of which is comma separated keywords.  Essentially `keywords:leveldb,voxel` in the ui expands into `keywords:leveldb AND keywords:voxel` when the request is sent to elasticsearch.

http://npmsearch.com/query?q=keywords:leveldb+AND+keywords:voxel

**Comment by JimtotheB** [comment]
Cool. That is documented somewhere on the hosted site right? I could swear that I saw that in passing somewhere, but I couldn't find it again.
