### ISSUE TITLE
Not possible to find a valid npm package

### ISSUE THREAD

**Issue by Kamahl19** [solids/npmsearch#32]
It is not possible to find this package via npmsearch 

https://www.npmjs.com/package/hain-plugin-npm
http://npmsearch.com/?q=hain-plugin-npm

I have no idea where is the problem. Is it the package name?

**Comment by tmpvar** [comment]
Sometimes it takes a while for new packages to get indexed. http://npmsearch.com/?q=hain-plugin-npm is now available.
