### ISSUE TITLE
can't find an item by keyword

### ISSUE THREAD

**Issue by zaggino** [solids/npmsearch#34]
hi,

doing search: http://npmsearch.com/query?q=keywords:brackets-extension&fields=name

returns a number of items, but at least one (https://github.com/zaggino/brackets-eslint/issues/34) is missing: https://www.npmjs.com/package/brackets-eslint

you can see on the npm website that "brackets-extension" keyword is there and this was actually working for a long time (it was being found and returned)

**Comment by tmpvar** [comment]
I believe this was an issue with the indexer stalling, closing for now
