### ISSUE TITLE
SSL Cert error

### ISSUE THREAD

**Issue by mattrayner** [solids/npmsearch#36]
There appears to be an SSL cert error on npmsearch.com

This is more an FYI than anything else

**Comment by tmpvar** [comment]
@mattrayner what is the error that you are seeing?

**Comment by wKovacs64** [comment]
A [Qualys Report](https://www.ssllabs.com/ssltest/analyze.html?d=npmsearch.com) seems to indicate an incomplete chain, missing the `GlobalSign Domain Validation CA - SHA256 - G2` intermediate.

**Comment by tmpvar** [comment]
I'll be transitioning over to letsencrypt here in a week or two, will revisit then

**Comment by tmpvar** [comment]
So it's been a bit more than a week, but I've added the intermediate cert and the cert error should be gone for the time being.  SSL renewal work tracked in #39
