### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by jdubois** [solids/npmsearch#38]
The certificate is wrong when going to https://npmsearch.com

**Comment by tmpvar** [comment]
@jdubois What do you mean by "wrong"? What error are you seeing on what browser, etc?

**Comment by jdubois** [comment]
There is a "Your connection is not private" error message on Chrome when going to https://npmsearch.com and it looks like the SSL certificate is wrong

**Comment by jdubois** [comment]
By the way, we are quite heavy users of your service through https://jhipster.github.io/modules/marketplace/#/list (that should send you at least 60K requests per month)

**Comment by tmpvar** [comment]
odd, I'm not seeing that in chrome (Version 53.0.2785.116 (64-bit)).

![screen shot 2016-09-28 at 4 38 40 pm](https://cloud.githubusercontent.com/assets/46673/18931443/35c863be-859a-11e6-844a-00db57b48bb1.png)

**Comment by jdubois** [comment]
That's strange, I only have the issue with Chrome, and not Firefox!! And Chrome looks broken, it can't show me the certificate.
Please note I just upgraded to Mac OS X Sierra... I'm checking this.

**Comment by tmpvar** [comment]
Oh, hrm. I think this has something to do with the cert chain. I'll be migrating to letsencrypt here in a few days, my guess is that this issue will be resolved then.

**Comment by jdubois** [comment]
Here's all I got, when I click on "view certificate" I have an empty box!!
<img width="764" alt="screenshot 2016-09-28 22 42 25" src="https://cloud.githubusercontent.com/assets/316835/18931549/f5faff34-85cc-11e6-9d0a-b6b202f4e764.png">

**Comment by tmpvar** [comment]
ugh, that is super annoying. I'll try to make the switch by the end of the week (the current certificate expires early next month anyhow)

**Comment by jdubois** [comment]
And it also works with Safari... So definitely something with Chrome, that's really strange.

**Comment by tmpvar** [comment]
@jdubois can you try again in Chrome?

**Comment by jdubois** [comment]
Oh, it's working. Magic :-)
What did you do?

Anyway, thanks again for your help, and for the service you provide. Once again, we are very heavy users (it's also used on our frontpage).

That makes me think I need to thank you on https://jhipster.github.io/thanks/ - I'm doing this right away

**Comment by tmpvar** [comment]
No worries, I had forgotten to install the intermediate cert.  Will revisit this when migrating to letsencrypt (tracked in #39).

Thanks!
