### ISSUE TITLE
Could not connect to elasticsearch

### ISSUE THREAD

**Issue by toadkicker** [solids/npmsearch#50]
Using the example in the README gives a 500:

```
curl "http://npmsearch.com/query?q=dom&fields=name"
> Could not connect to elasticsearch
```

**Comment by tmpvar** [comment]
Hey, sorry for the delay! This has been fixed (ae0a833b1224a68eb827747f29580ba6cb3b257b) and deployed.

Feel free to re-open this if the problem persists.
