### ISSUE TITLE
sorting results in no results

### ISSUE THREAD

**Issue by shazron** [solids/npmsearch#54]
This results in zero results.
http://npmsearch.com/query/?fields=name,keywords,license,description,author,modified,homepage,version,rating&q=keywords:%22ecosystem:cordova%22&sort=rating:desc

The same URL without the `sort` query param has results:

http://npmsearch.com/query/?fields=name,keywords,license,description,author,modified,homepage,version,rating&q=keywords:%22ecosystem:cordova%22

**Comment by shazron** [comment]
Context: we use `npmsearch` to search for plugins for `Apache Cordova`: http://cordova.apache.org/plugins/

We have been using it successfully with the `sort` param before, but now we get zero results. This only occurred since last week, when we got reports from our users:

1. https://twitter.com/edeortuzar/status/843310576101146625
2. https://twitter.com/kumakumadev/status/843149557127155712
3. https://twitter.com/quangv/status/842925319254360064
4. https://twitter.com/skumarSDsoft/status/842677001433497600

There are no errors in our Web Inspector console, and tracking it down resulted in the report description results above.

**Comment by tmpvar** [comment]
Ah, sorry about this! The underlying ES mappings have changed a bit and I missed the `sort` param's `rating` => `score` change.  This has been fixed (01b70ae2ab13fe515c1cd6a2a5ad51805d16cf07) and deployed. 

Feel free to reopen if this issue persists - my apologies for the inconvenience!

**Comment by shazron** [comment]
Thank you for the fast response! 💯
