### ISSUE TITLE
Cannot get 'modified' field using the query API

### ISSUE THREAD

**Issue by shazron** [solids/npmsearch#55]
Thanks for fixing #54! Now that we get results again we noticed that we are not getting the 'modified' field even though it was requested. I've tried to go through the source and commits to see perhaps whether it has been renamed, but I couldn't find any information (perhaps its related to the ES mappings you mentioned in #54), and I'm wondering if you can help guide us.

Example query:
http://npmsearch.com/query/?fields=name,keywords,modified,rating&q=keywords:%22ecosystem:cordova%22&sort=rating:desc

Expected result:
Each of the results contains a `modified` field.

Actual result:
Each of the results does not contain a `modified` field.

**Comment by tmpvar** [comment]
I didn't see this until now, my bad! You are right, the mappings changed where this lives, I'll get a patch going to fix the backwards compat.

**Comment by tmpvar** [comment]
fixed (acd071f41a096724489a420e8ae4cddc4f3c0348) and deployed - feel free to reopen if the issue persists

**Comment by shazron** [comment]
Thank you again! 💯
